#!/bin/sh
fileList=$(git diff --diff-filter=d --cached --name-only)

phpFiles=$(echo "$fileList" | grep -E '\.(php)$')

tools/php-cs-fixer/vendor/bin/php-cs-fixer fix app

# エラーがあれば、コミットさせない
if [ $? -gt 0 ]; then
	printf "エラーが発生しました。"
	exit 1
fi

printf "問題なし"

# エラーがなければ、Linterが変更した差分を取り込んでコミット
git add ${phpFiles[@]}